### ISSUE TITLE
Creepers don't drop gunpowder

### ISSUE THREAD

**Issue by VindSole** [Tater-Certified/Potatoptimize#23]
Basically title, no idea which optimization causes this.

**Comment by QPCrummer** [comment]
This may just be the weirdest issue of Potatopimze so far. That being said, I am almost certain it is an issue with one of my random optimizations. Can you try putting `mixin.random.generators = false` in the config and seeing if that fixes the issue?

**Comment by Libreh** [comment]
I have narrowed it down to `mixin.random.entity`.

**Comment by QPCrummer** [comment]
The culprit is `mixin.random.math`. A lot of the methods in there are using incorrect versions. It has also occurred to me that the optimizations located in there aren't needed anymore since I optimized the actual random number generator instead. So in the next release, the majority of `mixin.random.math` will be removed, fixing this issue any probably many others as well.

**Comment by Libreh** [comment]
Oh wait yeah it is `mixin.random.math`, put the wrong one, woops.

**Comment by VindSole** [comment]
That's weird since I just checked and I have mixin.random.math set to false because of the block gap bug, so it could not be that or it doesn't get disabled completely

**Comment by QPCrummer** [comment]
No idea, but that was the issue for me. With it removed it no longer causes any issues

**Comment by QPCrummer** [comment]
Creepers and all other mobs should drop loot now with this new version: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.7

**Comment by VindSole** [comment]
Fixed!

**Comment by QPCrummer** [comment]
Epic! Thanks for reporting this.
