### ISSUE TITLE
def v6 incompatible with Doormat

### ISSUE THREAD

**Issue by sternschnaube** [Tater-Certified/Potatoptimize#24]
https://pastebin.com/raw/Xwn8FmPP

https://modrinth.com/mod/doormat

Could you help please @axialeaa? 😄

**Comment by QPCrummer** [comment]
First off, I want to make it clear that it is not any other mod developer's responsibility to provide compatibility to my mod. If there is an issue I should be the one to fix it as my mod is extremely invasive compared to many other fabric mods. If I find a solution that can be applied to the mod in question, then I will submit a PR. In many cases compatibility is not possible so the best I can do is disable my optimization in order to preserve compatibility.

With this specific issue, the optimization in question is a recent one I added that stored if a chunk is a slime chunk in the Chunk class. This significantly reduces the amount of computations done when a slime spawns. However it seems doormat is trying to inject code into a place where I have an Overwrite. Typically Overwrites are a very bad coding practice, however the benefit of them is that they are very easy to implement. In order to fix compatibility I will need to split my Overwrite into multiple different Mixins. I will fix this for the next release.

**Comment by QPCrummer** [comment]
This version should contain the fix for doormat: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.7

**Comment by sternschnaube** [comment]
Thanks for the fix, and for Noctural Bats aswell 😊

**Comment by axialeaa** [comment]
thanks for the compatibility! appreciate it massively <3
