### ISSUE TITLE
Mixin conflict with nocturnal bats

### ISSUE THREAD

**Issue by unix-supremacist** [Tater-Certified/Potatoptimize#27]
nocturnal bats from [here](https://modrinth.com/mod/nocturnal-bats/versions)

https://pastebin.com/rxs9tNtv

extra note, this can be temporarily fixed by disabling the potatooptimize mixin

**Comment by QPCrummer** [comment]
According to the MixinExtras developer, compat with this mod isn't really possible due to the way Mixin works. I asked if I could force my Mixin to be applied before theirs (which in theory would fix the issue), but they unfortunately said it isn't possible. I'll try messing with it a bit more, but I don't think it will be possible to make this mod compatible by default. 

I would add an automatic disable for it, but I haven't decided if I should add mods like this to the mod compat list

**Comment by QPCrummer** [comment]
I ended up adding the mod to the compatibility list anyways. If I end up figuring out a way to get this mod working with my optimization, I'll fix it. For now it just disables my optimization. 
https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.7

**Comment by unix-supremacist** [comment]
yep that fixes the conflict :+1:

**Comment by QPCrummer** [comment]
Cool! Thanks for reporting it
