### ISSUE TITLE
Incompatibility with quilt

### ISSUE THREAD

**Issue by xboct02** [Tater-Certified/Potatoptimize#6]
---- Quilt Loader: Failed to load ----
Date/Time: 2024/05/29 12:20:43.3392
Quilt Loader Version: 0.25.0

-- Error 1 --

potatoptimize requires version [0.15.9, ∞) of fabricloader, which is missing!

- <mods>/potatoptimize-0.0.1-1.20.1.jar

-- Plugin State --

Cycle number = 1
Cycle Step = SOLVE

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)

**Comment by QPCrummer** [comment]
This is due to Quilt Loader not supporting the version of Fabric Loader I put in my mod json. I will fix this in a future release, however if you want a simple fix right now, you can open the jar file with a program like 7Zip and edit the fabric-mod.json. In that you’ll find a line that mentioned the fabric loader. Delete the version it has there and change it to “*”. Then save the file and restart.

**Comment by QPCrummer** [comment]
This has now been fixed and will be in the next release: `mc1.21-0.0.1-dev.6`.

I will close this issue once that version is out in the next few days.

**Comment by QPCrummer** [comment]
Fixed in this version: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.6
