### ISSUE TITLE
Compability with Stutterfix?

### ISSUE THREAD

**Issue by Rad586** [Tater-Certified/Potatoptimize#8]
https://modrinth.com/mod/stutterfix
Stutterfix tweaks worker threads count and thread priority, but potatoptimize replaces worker thread(`mixin.logic.worker_thread`) and tweaks resource values(`mixin.logic.main_thread`). I was wondering if they work well with each other.
Since I have no experience of modding, I tested using spark: 
![image](https://github.com/Tater-Certified/Potatoptimize/assets/99306685/b825d17f-c24f-4086-a247-263731069707)
![image](https://github.com/Tater-Certified/Potatoptimize/assets/99306685/75b7e0f4-d677-46ee-899d-2d173aaf79b5)
Seems the `Worker-Main` thread was replaced by `PotatoptimizeWorkerThread-Main` with less counts.

Also, smoothboot tweaks the count of threads, and modernfix tweaks the priority of threads, I was also wondering if these features are compatible with potatoptimize.

**Comment by QPCrummer** [comment]
I also tweak the priority of the threads after I replace them. Modernfix may try to change the priority of the original thread, but it shouldn't affect anything as that thread is not used anymore. 

Additionally, if Modernfix is present, `mixin.logic.worker_thread` disables itself as it has similar code that is probably higher quality overall than my implementation.

I'm not sure if stutterfix would be beneficial in this case. Since thread priority is already set by my mod, it probably won't be changed by stutterfix. I suppose it could alter the amount of threads present, but I'm not sure if it'd be compatible with my implementation.

**Comment by QPCrummer** [comment]
Stutterfix is now going to be completely compatible with Potatoptimize as I will disable my workerthread and main thread optimizations to prefer Stufferfix's configuration. Now I will say that *most likely* this will reduce performance overall, however it could reduce CPU usage, and hence improve frame times on the client. If you are on a server, I honestly wouldn't recommend Stutterfix as I see no use for it unless you are running a server on your local machine and don't want it to be bogged down.

I will close this as resolved once I release the new version of Potatoptimize `mc1.21-0.0.1-dev.6`

**Comment by QPCrummer** [comment]
Stutterfix should have no issues in this version and beyond: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.6
